language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  ## udagram-api-feed
  - docker build -t udagram-api-feed:v1 ./udagram-api-feed
  - docker tag udagram-api-feed:v1 trind7/udagram-api-feed:v1
  ## udagram-api-user
  - docker build -t udagram-api-user:v1 ./udagram-api-user  
  - docker tag udagram-api-user:v1 trind7/udagram-api-user:v1
  ## uudagram-frontend
  - docker build -t udagram-frontend:v1 ./udagram-frontend
  - docker tag udagram-frontend:v1 trind7/udagram-frontend:v1
  ## udagram-reverseproxy
  - docker build -t udagram-reverseproxy:v1 ./udagram-reverseproxy
  - docker tag udagram-reverseproxy:v1 trind7/udagram-reverseproxy:v1

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push trind7/udagram-api-feed:v1
  - docker push trind7/udagram-api-user:v1
  - docker push trind7/udagram-api-frontend:v1
  - docker push trind7/udagram-api-reverseproxy:v1