version: 2.1

# Define the jobs we want to run for this project
jobs:
  deloyment:
    docker:      
      - image: cimg/node:16.20
    steps:
      - checkout
      - run: node --version
      - setup_remote_docker:
            version: 20.10.14
            docker_layer_caching: true
      - run:
            name: Build Docker Container
            command: |
                docker --version
                # Requested access to the resource
                docker login -u $DOCKER_USER -p $DOCKER_PASS
                # Build image and add a descriptive tag and push images to a docker repository
                # udagram-api-feed
                echo 'udagram-api-feed'
                docker build -t udagram-api-feed:v3 ./udagram-api-feed
                docker tag udagram-api-feed:v3 trind7/udagram-api-feed:v3 
                docker push trind7/udagram-api-feed:v3 
                # udagram-api-user
                echo 'udagram-api-user'
                docker build -t udagram-api-user:v3 ./udagram-api-user  
                docker tag udagram-api-user:v3 trind7/udagram-api-user:v3
                docker push trind7/udagram-api-user:v3
                # frontend
                echo 'frontend'
                docker build -t udagram-frontend:v3 ./udagram-frontend
                docker tag udagram-frontend:v3 trind7/udagram-frontend:v3
                docker push trind7/udagram-frontend:v3
                # reverseproxy
                echo 'reverseproxy'
                docker build -t udagram-reverseproxy:v3 ./udagram-reverseproxy
                docker tag udagram-reverseproxy:v3 trind7/udagram-reverseproxy:v3
                docker push trind7/udagram-reverseproxy:v3
# Orchestrate our job run sequence
workflows:
  default:
    jobs:
      - deloyment