apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    part: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      part: backend-user
  template:
    metadata:
      labels:
        part: backend-user
    spec:
      containers:
      - name: udagram-api-user
        image: trind7/udagram-api-user:v3
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"        
        ports:
        - containerPort: 8080
        env:
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: POSTGRES_HOST
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: POSTGRES_DB
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: POSTGRES_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: POSTGRES_PASSWORD
          - name: AWS_BUCKET
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: AWS_BUCKET
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: AWS_REGION
          - name: AWS_PROFILE
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: AWS_PROFILE
          - name: URL
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: URL          
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: env-config
                key: JWT_SECRET
        volumeMounts:
          - name: aws-secret
            mountPath: "/root/.aws/"
            readOnly: true
      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret
        