apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udagram-eksctl-cluster
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t3.large
    desiredCapacity: 2
    volumeSize: 20
  - name: ng-2
    instanceType: t3.large
    desiredCapacity: 2
    volumeSize: 20