apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    part: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      part: reverseproxy
  template:
    metadata:
      labels:
        part: reverseproxy
    spec:
      containers:
      - name: udagram-reverseproxy
        image: trind7/udagram-reverseproxy
        ports:
        - containerPort: 8080